<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <style>
            body{
                font-family:DejaVu Sans,sans-serif;
                color:#222;
                font-size:12px
            }
            .head{
                text-align:center;
                border-bottom:2px solid #07536c;
                padding-bottom:15px
            }
            .head h1{
                color:#07536c;
                margin:10px 0 2px;
                font-size:20px
                }
            .meta{
                text-align:right;
                margin:20px 0
            }
            .content{
                line-height:1.8;
                margin-top:30px
            }
            .box{
                border:1px solid #bbb;
                padding:18px;
                margin-top:25px
            }
            .signature{
                margin-top:70px;
                text-align:center
            }
            .footer{
                margin-top:80px;
                font-size:9px;
                color:#777;
                text-align:center
            }
        </style>
    </head>
    <body>
        <div class="document-header">

    <div class="header-logo left-logo">
        <img src="{{ public_path('images/logo.png') }}"
             alt="Barangay San Bartolome Logo">
    </div>

    <div class="header-center">
        <div class="republic">REPUBLIC OF THE PHILIPPINES</div>
        <div class="province">PROVINCE OF SORSOGON</div>
        <div class="municipality">MUNICIPALITY OF SANTA MAGDALENA</div>
        <div class="barangay">BARANGAY SAN BARTOLOME</div>

        <div class="office-title">
            OFFICE OF THE BARANGAY
        </div>
    </div>

    <div class="header-logo right-logo">
        <img src="{{ public_path('images/Sta_Magdalena_logo.png') }}"
             alt="Santa Magdalena Logo">
    </div>

</div>
        <div class="meta">Document No.: 
            <strong>{{ $document->document_no }}</strong>
            <br>Date Issued: {{ $document->issued_date->format('F d, Y') }}
        </div>
        <div class="content">TO WHOM IT MAY CONCERN:
            <p>This is to certify that <strong>{{ $document->business->owner_name }}</strong>, owner/operator of <strong>{{ $document->business->business_name }}</strong>, located at {{ $document->business->address }}, is recorded in the barangay business registry.</p>
            <p>This document is issued for <strong>{{ $document->purpose ?: 'official barangay purposes' }}</strong>.</p>
            <div class="box">
                <strong>Business Permit No.:</strong> {{ $document->business->permit_number }}
                <br>
                <strong>Business Category:</strong> {{ $document->business->category }}
                <br>
                <strong>Landmark:</strong> {{ $document->business->landmark ?: '—' }}
            </div>
        </div>
        <div class="signature">
            <strong>{{ $document->issuer->name ?? 'Barangay Secretary' }}</strong>
            <br>
            Barangay Secretary
        </div>
        <div class="footer">Generated by REGISTRA — Barangay Management System</div>
    </body>
</html>