<!DOCTYPE html>
<html>
<head>

    <meta charset="UTF-8">
    <title>Payment Transaction Report</title>
    <style>
        @page {
            margin: 30px;
        }

        * {
            box-sizing: border-box;
        }

        body {
            margin: 0;
            padding: 0;

            font-family: DejaVu Sans, sans-serif;

            color: #174f66;

            font-size: 10px;
        }

        .pdf-header {
            margin-bottom: 20px;

            padding-bottom: 12px;

            border-bottom: 2px solid #005676;
        }

        .pdf-header h1 {
            margin: 0;

            color: #005676;

            font-size: 20px;
        }

        .pdf-header p {
            margin: 5px 0 0;

            color: #6d8c99;

            font-size: 10px;
        }

        .report-meta {
            margin-bottom: 15px;

            padding: 9px 12px;

            background: #f1f8fa;

            border: 1px solid #d8edf5;

            border-radius: 5px;
        }

        table {
            width: 100%;

            border-collapse: collapse;

            table-layout: fixed;
        }

        th {
            padding: 8px;

            background: #eaf6fa;

            border: 1px solid #cde4ec;

            color: #315f72;

            font-size: 8px;

            text-align: left;
        }

        td {
            padding: 8px;

            border: 1px solid #dcebef;

            font-size: 9px;

            vertical-align: middle;
        }

        .amount {
            font-weight: bold;

            color: #005676;
        }

        .footer {
            margin-top: 15px;

            padding-top: 8px;

            border-top: 1px solid #d8edf5;

            color: #7898a7;

            font-size: 8px;
        }

    </style>

</head>

<body>

    <div class="pdf-header">

        <h1>Payment Transaction Report</h1>

        <p>
            Barangay Treasurer — Payment Collection Records
        </p>

    </div>


    <div class="report-meta">

        <strong>Total Transactions:</strong>
        {{ $payments->count() }}

        &nbsp;&nbsp;&nbsp;

        <strong>Generated:</strong>
        {{ now()->format('M d, Y') }}

    </div>


    <table>

        <thead>

            <tr>
                <th>REFERENCE</th>
                <th>DATE</th>
                <th>BUSINESS</th>
                <th>TRANSACTION</th>
                <th>AMOUNT</th>
                <th>RECEIVED BY</th>
            </tr>

        </thead>

        <tbody>

            @forelse($payments as $payment)

                <tr>

                    <td>
                        {{ $payment->reference_no }}
                    </td>

                    <td>
                        {{ $payment->payment_date?->format('M d, Y') }}
                    </td>

                    <td>
                        {{ $payment->business->business_name ?? 'N/A' }}
                    </td>

                    <td>
                        {{ $payment->assessment->transaction_type ?? 'N/A' }}
                    </td>

                    <td class="amount">
                        ₱{{ number_format($payment->amount, 2) }}
                    </td>

                    <td>
                        {{ $payment->receiver->name ?? 'Barangay Treasurer' }}
                    </td>

                </tr>

            @empty

                <tr>

                    <td colspan="6" style="text-align:center;">
                        No payment transactions found.
                    </td>

                </tr>

            @endforelse

        </tbody>

    </table>


    <div class="footer">
        Generated by REGISTRA
    </div>

</body>
</html>